### ISSUE TITLE
Tracking Issue for Mod Lint

### ISSUE THREAD

**Issue by trumank** [trumank/drg-mod-integration#39]
I have a small utility I use for doing some quick automated checks on mods: https://github.com/trumank/drg-mod-tools

There could be a developer option to run this automatically on all mods and notify the user of any problems found. This could be useful for both debugging integration problems but also to help mod developers troubleshoot their own mods. The integrator also has information on contents of the DRG pak as well as other mods it's being loaded with so it's fully equipped to inform the user of possible mod conflicts or expected file replacements as well.

### Lints

- [x] Check for mod conflicts.
- [ ] Check for incorrect inclusion of third party dependencies.
- [ ] Check for differing versions of common libraries (`_Interop`, `_AssemblyStorm/Common`)
- [x] Check for split uasset/uexp pairs.
- [x] Check pak version.
- [x] Check for non-asset files.
- [x] Check for exactly one pak per archive.
- [x] Check AssetRegistry.bin.
- [x] Check for unmodified base game assets.
- [x] Check for shader files.
- [ ] Check if mod will auto-verify.

**Comment by Buckminsterfullerene02** [comment]
Can you implement modio "will it auto-verify" lint too?

**Comment by jieyouxu** [comment]
> Can you implement modio "will it auto-verify" lint too?

This lint is implemented in PR #124.
