### ISSUE TITLE
Tracking issue for GUI refactoring

### ISSUE THREAD

**Issue by jieyouxu** [trumank/drg-mod-integration#40]
Originally from comment https://github.com/trumank/drg-mod-integration/pull/30#issuecomment-1668352993. This issue keeps track of GUI refactoring effort.

- [ ] Split async GUI logic into its own module.
- [ ] Unify "GUI locking" check into just a single function call or flag.
  * Currently every action that can possibly lock the entire GUI is checked individually in each place its needed which is verbose and error prone.
- [ ] Modularize the current "profile view" so it's possible to do things like put it in a window or create multiple windows each showing a different profile.
- [ ] Modularize the current "select/add/remove/rename `thing`" component so it can be shared between many types of `thing`s.
