### ISSUE TITLE
Tracking issue for versioned configurations and migrations

### ISSUE THREAD

**Issue by jieyouxu** [trumank/drg-mod-integration#41]
- [x] Version the current config in internal state.
- [x] Version the current profiles in internal state.
- [x] Version the current cache in internal state.
- [x] Implement migrations for unversioned config -> versioned config.
- [x] Implement migrations for unversioned profiles-> versioned profiles.
- [x] Implement migrations for unversioned cache-> versioned cache.

These are in preparation for the future mod groups feature #14 as well as future changes to internal state and thus impacts user config.

**Comment by jieyouxu** [comment]
Implemented in #42.
